// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kguxonhyuqadvnmdgzow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndXhvbmh5dXFhZHZubWRnem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODMxMjEsImV4cCI6MjA2NTQ1OTEyMX0.Hl7oTTIK9bVBBr_QZJVrZaF4RAyBQayHyEizMzOKXxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);